//// <auto-generated/>
//// This file combines all generated partial classes for ClassesWithNamespacesTestCases
//// In reality, each would be in a separate file as indicated by comments

//namespace PlacesOfInterestMod.IntegrationTests;

//// ============================================================================
//// File: PlacesOfInterestMod.IntegrationTests.ClassesWithNamespacesTestCases.Demo0.g.cs
//// ============================================================================
//static partial class ClassesWithNamespacesTestCases
//{
//    partial class Demo0
//    {
//        private Demo0()
//        {
//            Some = new SomeNamespace(this);
//        }

//        private SomeNamespace Some { get; }

//        private partial class SomeNamespace
//        {
//            private readonly Demo0 _parent;

//            private SomeNamespace(Demo0 parent)
//            {
//                _parent = parent;
//            }

//            private Demo0 This { get => _parent; }
//        }
//    }
//}

//// ============================================================================
//// File: PlacesOfInterestMod.IntegrationTests.ClassesWithNamespacesTestCases.Demo1.g.cs
//// ============================================================================
//static partial class ClassesWithNamespacesTestCases
//{
//    partial class Demo1
//    {
//        protected Demo1()
//        {
//            X = new XNamespace(this);
//        }

//        protected XNamespace X { get; }

//        protected partial class XNamespace
//        {
//            private readonly Demo1 _parent;

//            protected XNamespace(Demo1 parent)
//            {
//                _parent = parent;
//                Y = new YNamespace(this);
//                Z = new ZNamespace(this);
//            }

//            protected Demo1 This { get => _parent; }

//            protected YNamespace Y { get; }
//            internal ZNamespace Z { get; }

//            protected partial class YNamespace
//            {
//                private readonly XNamespace _parent;

//                protected YNamespace(XNamespace parent)
//                {
//                    _parent = parent;
//                }

//                protected XNamespace X { get => _parent; }
//                protected Demo1 This { get => _parent._parent; }
//            }

//            internal partial class ZNamespace
//            {
//                private readonly XNamespace _parent;

//                internal ZNamespace(XNamespace parent)
//                {
//                    _parent = parent;
//                }

//                protected XNamespace X { get => _parent; }
//                protected Demo1 This { get => _parent._parent; }
//            }
//        }
//    }
//}

//// ============================================================================
//// File: PlacesOfInterestMod.IntegrationTests.ClassesWithNamespacesTestCases.Demo2.g.cs
//// ============================================================================
//static partial class ClassesWithNamespacesTestCases
//{
//    partial class Demo2
//    {
//        private Demo2()
//        {
//            W = new WNamespace(this);
//        }

//        private WNamespace W { get; }

//        private partial class WNamespace
//        {
//            private readonly Demo2 _parent;

//            private WNamespace(Demo2 parent)
//            {
//                _parent = parent;
//                Q = new QNamespace(this);
//            }

//            private Demo2 This { get => _parent; }

//            internal QNamespace Q { get; }

//            internal partial class QNamespace
//            {
//                private readonly WNamespace _parent;

//                internal QNamespace(WNamespace parent)
//                {
//                    _parent = parent;
//                }

//                private WNamespace W { get => _parent; }
//                private Demo2 This { get => _parent._parent; }
//            }
//        }
//    }
//}

//// ============================================================================
//// File: PlacesOfInterestMod.IntegrationTests.ClassesWithNamespacesTestCases2.Demo0.g.cs
//// ============================================================================
//static partial class ClassesWithNamespacesTestCases2
//{
//    partial class Demo0
//    {
//        private Demo0()
//        {
//            Some = new SomeNamespace(this);
//        }

//        private SomeNamespace Some { get; }

//        private partial class SomeNamespace
//        {
//            private readonly Demo0 _parent;

//            private SomeNamespace(Demo0 parent)
//            {
//                _parent = parent;
//            }

//            private Demo0 This { get => _parent; }
//        }
//    }
//}

//// ============================================================================
//// File: PlacesOfInterestMod.IntegrationTests.ClassesWithNamespacesTestCases2.Demo1.g.cs
//// ============================================================================
//static partial class ClassesWithNamespacesTestCases2
//{
//    partial class Demo1
//    {
//        protected Demo1()
//        {
//            X = new XNamespace(this);
//        }

//        protected XNamespace X { get; }

//        protected partial class XNamespace
//        {
//            private readonly Demo1 _parent;

//            protected XNamespace(Demo1 parent)
//            {
//                _parent = parent;
//                Y = new YNamespace(this);
//                Z = new ZNamespace(this);
//            }

//            protected Demo1 This { get => _parent; }

//            protected YNamespace Y { get; }
//            internal ZNamespace Z { get; }

//            protected partial class YNamespace
//            {
//                private readonly XNamespace _parent;

//                protected YNamespace(XNamespace parent)
//                {
//                    _parent = parent;
//                }

//                protected XNamespace X { get => _parent; }
//                protected Demo1 This { get => _parent._parent; }
//            }

//            internal partial class ZNamespace
//            {
//                private readonly XNamespace _parent;

//                internal ZNamespace(XNamespace parent)
//                {
//                    _parent = parent;
//                }

//                protected XNamespace X { get => _parent; }
//                protected Demo1 This { get => _parent._parent; }
//            }
//        }
//    }
//}

//// ============================================================================
//// File: PlacesOfInterestMod.IntegrationTests.ClassesWithNamespacesTestCases2.Demo2.g.cs
//// ============================================================================
//static partial class ClassesWithNamespacesTestCases2
//{
//    partial class Demo2
//    {
//        private Demo2()
//        {
//            W = new WNamespace(this);
//        }

//        private WNamespace W { get; }

//        private partial class WNamespace
//        {
//            private readonly Demo2 _parent;

//            private WNamespace(Demo2 parent)
//            {
//                _parent = parent;
//                Q = new QNamespace(this);
//            }

//            private Demo2 This { get => _parent; }

//            internal QNamespace Q { get; }

//            internal partial class QNamespace
//            {
//                private readonly WNamespace _parent;

//                internal QNamespace(WNamespace parent)
//                {
//                    _parent = parent;
//                }

//                private WNamespace W { get => _parent; }
//                private Demo2 This { get => _parent._parent; }
//            }
//        }
//    }
//}
