// NOTE: Ignore generated code warnings.
#pragma warning disable
using Vintagestory.API.Common;
using Vintagestory.API.Config;

namespace PlacesOfInterestMod;

// NOTE: SumSharp generates code without correct namespaces.
//[UnionCase("Success", typeof(LocalizedText))]
//[UnionCase("Error", typeof(LocalizedText))]
public sealed partial class LocalizedTextCommandResult
{
    public static implicit operator TextCommandResult(LocalizedTextCommandResult result)
    {
        return result.Match(
            Success: x => TextCommandResult.Success(Lang.Get(x.Key, x.Args)),
            Error: x => TextCommandResult.Error(Lang.Get(x.Key, x.Args)),
            () => TextCommandResult.Error(""));
    }
}

// NOTE: Generated by SumSharp. Do not modify by hand.
public partial class LocalizedTextCommandResult : global::System.IEquatable<LocalizedTextCommandResult>
{
    private PlacesOfInterestMod.LocalizedText _PlacesOfInterestMod_LocalizedText = default;

    ///<summary>The zero-based index of the case held by the discriminated union</summary>
    public int Index { get; }

    private LocalizedTextCommandResult(int index)
    {
        System.Diagnostics.Debug.Assert(index >= 0 && index < 2);

        Index = index;
    }

    ///<summary>Compares two LocalizedTextCommandResult instances for equality. The two instances are equal iff they have the same Index and their underlying values compare equal using Object.Equals</summary>
    public bool Equals(LocalizedTextCommandResult? other)
    {
        if (other is null) return false;
        if (Index != other.Index) return false;

        return Index switch
        {
            0 => Equals(AsSuccessUnsafe, other.AsSuccessUnsafe),
            1 => Equals(AsErrorUnsafe, other.AsErrorUnsafe),
        };
    }

    ///<summary>Compares a LocalizedTextCommandResult instance and another object for equality. The LocalizedTextCommandResult instance is equal to the other object iff 
    /// the other object is a LocalizedTextCommandResult and they have the same Index and their underlying values compare equal using Object.Equals</summary>
    public override bool Equals(object? obj)
    {
        if (obj is null) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != GetType()) return false;

        return Equals(System.Runtime.CompilerServices.Unsafe.As<LocalizedTextCommandResult>(obj));
    }

    public override int GetHashCode()
    {
        return Index switch
        {
            0 => System.HashCode.Combine(0, AsSuccessUnsafe),
            1 => System.HashCode.Combine(1, AsErrorUnsafe),
        };
    }

    ///<summary>Compares two LocalizedTextCommandResult instances for equality using IEquatable<LocalizedTextCommandResult>.Equals</summary>
    public static bool operator ==(LocalizedTextCommandResult left, LocalizedTextCommandResult right) => left.Equals(right);

    ///<summary>Compares two LocalizedTextCommandResult instances for inequality using IEquatable<LocalizedTextCommandResult>.Equals</summary>
    public static bool operator !=(LocalizedTextCommandResult left, LocalizedTextCommandResult right) => !left.Equals(right);

    ///<summary>A static function that creates a LocalizedTextCommandResult that holds a Success</summary>
    public static LocalizedTextCommandResult Success(PlacesOfInterestMod.LocalizedText value)
    {
        var ret = new LocalizedTextCommandResult(0);

        ret._PlacesOfInterestMod_LocalizedText = value;

        return ret;
    }

    ///<summary>A static function that creates a LocalizedTextCommandResult that holds a Error</summary>
    public static LocalizedTextCommandResult Error(PlacesOfInterestMod.LocalizedText value)
    {
        var ret = new LocalizedTextCommandResult(1);

        ret._PlacesOfInterestMod_LocalizedText = value;

        return ret;
    }

    private PlacesOfInterestMod.LocalizedText AsSuccessUnsafe
    {
        get
        {
            System.Diagnostics.Debug.Assert(Index == 0);

            return _PlacesOfInterestMod_LocalizedText;
        }
    }

    ///<summary>The Success value, if present. Throws InvalidOperationException if the LocalizedTextCommandResult does not hold a Success</summary>
    ///<exception cref="InvalidOperationException">Thrown if the LocalizedTextCommandResult does not hold a Success</exception>
    public PlacesOfInterestMod.LocalizedText AsSuccess => Index == 0 ? AsSuccessUnsafe : throw new global::System.InvalidOperationException($"Attempted to access case index 0 but index is {Index}");

    ///<summary>The Success value, if present. Otherwise default(PlacesOfInterestMod.LocalizedText)</summary>
    public PlacesOfInterestMod.LocalizedText? AsSuccessOrDefault => Index == 0 ? AsSuccessUnsafe : default;

    ///<summary>Returns the Success value, if present. Otherwise returns <paramref name="defaultValue"/></summary>
    ///<param name="defaultValue">The default value to return if the LocalizedTextCommandResult does not hold a Success</param>
    public PlacesOfInterestMod.LocalizedText AsSuccessOr(PlacesOfInterestMod.LocalizedText defaultValue) => Index == 0 ? AsSuccessUnsafe : defaultValue;

    ///<summary>Returns the Success value, if present. Otherwise returns the result of invoking <paramref name="defaultValueFactory"/></summary>
    ///<param name="defaultValueFactory">Provides the default value to return if the LocalizedTextCommandResult does not hold a Success</param>
    public PlacesOfInterestMod.LocalizedText AsSuccessOr(global::System.Func<PlacesOfInterestMod.LocalizedText> defaultValueFactory) => Index == 0 ? AsSuccessUnsafe : defaultValueFactory();

    ///<summary>Returns a global::System.Threading.Tasks.ValueTask wrapping the Success value, if present. Otherwise returns the result of invoking <paramref name="defaultValueFactory"/></summary>
    ///<param name="defaultValueFactory">Provides the default value to return if the LocalizedTextCommandResult does not hold a Success</param>
    public global::System.Threading.Tasks.ValueTask<PlacesOfInterestMod.LocalizedText> AsSuccessOr(global::System.Func<global::System.Threading.Tasks.Task<PlacesOfInterestMod.LocalizedText>> defaultValueFactory) => Index == 0 ? global::System.Threading.Tasks.ValueTask.FromResult(AsSuccessUnsafe) : new global::System.Threading.Tasks.ValueTask<PlacesOfInterestMod.LocalizedText>(defaultValueFactory());

    private PlacesOfInterestMod.LocalizedText AsErrorUnsafe
    {
        get
        {
            System.Diagnostics.Debug.Assert(Index == 1);

            return _PlacesOfInterestMod_LocalizedText;
        }
    }

    ///<summary>The Error value, if present. Throws InvalidOperationException if the LocalizedTextCommandResult does not hold a Error</summary>
    ///<exception cref="InvalidOperationException">Thrown if the LocalizedTextCommandResult does not hold a Error</exception>
    public PlacesOfInterestMod.LocalizedText AsError => Index == 1 ? AsErrorUnsafe : throw new global::System.InvalidOperationException($"Attempted to access case index 1 but index is {Index}");

    ///<summary>The Error value, if present. Otherwise default(PlacesOfInterestMod.LocalizedText)</summary>
    public PlacesOfInterestMod.LocalizedText? AsErrorOrDefault => Index == 1 ? AsErrorUnsafe : default;

    ///<summary>Returns the Error value, if present. Otherwise returns <paramref name="defaultValue"/></summary>
    ///<param name="defaultValue">The default value to return if the LocalizedTextCommandResult does not hold a Error</param>
    public PlacesOfInterestMod.LocalizedText AsErrorOr(PlacesOfInterestMod.LocalizedText defaultValue) => Index == 1 ? AsErrorUnsafe : defaultValue;

    ///<summary>Returns the Error value, if present. Otherwise returns the result of invoking <paramref name="defaultValueFactory"/></summary>
    ///<param name="defaultValueFactory">Provides the default value to return if the LocalizedTextCommandResult does not hold a Error</param>
    public PlacesOfInterestMod.LocalizedText AsErrorOr(global::System.Func<PlacesOfInterestMod.LocalizedText> defaultValueFactory) => Index == 1 ? AsErrorUnsafe : defaultValueFactory();

    ///<summary>Returns a global::System.Threading.Tasks.ValueTask wrapping the Error value, if present. Otherwise returns the result of invoking <paramref name="defaultValueFactory"/></summary>
    ///<param name="defaultValueFactory">Provides the default value to return if the LocalizedTextCommandResult does not hold a Error</param>
    public global::System.Threading.Tasks.ValueTask<PlacesOfInterestMod.LocalizedText> AsErrorOr(global::System.Func<global::System.Threading.Tasks.Task<PlacesOfInterestMod.LocalizedText>> defaultValueFactory) => Index == 1 ? global::System.Threading.Tasks.ValueTask.FromResult(AsErrorUnsafe) : new global::System.Threading.Tasks.ValueTask<PlacesOfInterestMod.LocalizedText>(defaultValueFactory());

    ///<summary>True if the LocalizedTextCommandResult holds a Success, false otherwise</summary>
    public bool IsSuccess => Index == 0;

    ///<summary>True if the LocalizedTextCommandResult holds a Error, false otherwise</summary>
    public bool IsError => Index == 1;

    ///<summary>Invokes the corresponding function with the underlying value held by the LocalizedTextCommandResult. Throws <see cref="SumSharp.MatchFailureException"/>
    /// if no handler or default handler is provided for the active case</summary>
    ///<exception cref="SumSharp.MatchFailureException">Thrown when no handler or default handler is provided for the active case</exception>
    public void Match(global::System.Action<PlacesOfInterestMod.LocalizedText>? Success = null, global::System.Action<PlacesOfInterestMod.LocalizedText>? Error = null, global::System.Action? _ = null)
    {
        switch (Index)
        {
            case 0:
                if (Success is not null) Success(AsSuccessUnsafe);
                else if (_ is not null) _();
                else throw new global::SumSharp.MatchFailureException("Success");

                break;
            case 1:
                if (Error is not null) Error(AsErrorUnsafe);
                else if (_ is not null) _();
                else throw new global::SumSharp.MatchFailureException("Error");

                break;
        }
    }

    ///<summary>Invokes the corresponding function with the underlying value held by the LocalizedTextCommandResult and returns the result. Throws
    /// <see cref="SumSharp.MatchFailureException"/> if no handler or default handler is provided for the active case</summary>
    ///<exception cref="SumSharp.MatchFailureException">Thrown when no handler or default handler is provided for the active case</exception>
    public TRet_ Match<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, TRet_>? Success = null, global::System.Func<PlacesOfInterestMod.LocalizedText, TRet_>? Error = null, global::System.Func<TRet_>? _ = null)
    {
        return Index switch
        {
            0 => Success is not null ? Success(AsSuccessUnsafe) : _ is not null ? _() : throw new global::SumSharp.MatchFailureException("Success"),
            1 => Error is not null ? Error(AsErrorUnsafe) : _ is not null ? _() : throw new global::SumSharp.MatchFailureException("Error"),
        };
    }
    ///<summary>If the LocalizedTextCommandResult holds a Success, invokes the <paramref name="handleSuccess"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise does nothing.</summary>
    ///<param name="handleSuccess">Function to be invoked with the PlacesOfInterestMod.LocalizedText value, if it exists.</param>
    public void IfSuccess(global::System.Action<PlacesOfInterestMod.LocalizedText> handleSuccess)
    {
        if (Index == 0)
        {
            handleSuccess(AsSuccessUnsafe);
        }
    }

    ///<summary>If the LocalizedTextCommandResult holds a Success, invokes the <paramref name="handleSuccess"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise invokes <paramref name="orElse"/>.</summary>
    ///<param name="handleSuccess">Function to be invoked with the Success value, if it exists.</param>
    ///<param name="orElse">Function to be invoked if the LocalizedTextCommandResult does not hold a Success</param>
    public void IfSuccessElse(global::System.Action<PlacesOfInterestMod.LocalizedText> handleSuccess, global::System.Action orElse)
    {
        if (Index == 0)
        {
            handleSuccess(AsSuccessUnsafe);
        }
        else
        {
            orElse();
        }
    }

    ///<summary>If the LocalizedTextCommandResult holds a Success, returns the result of invoking the <paramref name="handleSuccess"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns <paramref name="elseValue"/>.</summary>
    ///<param name="handleSuccess">Function to be invoked with the Success value, if it exists.</param>
    ///<param name="elseValue">Value to be returned if the LocalizedTextCommandResult does not hold a Success</param>
    public TRet_ IfSuccessElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, TRet_> handleSuccess, TRet_ elseValue) => Index == 0 ? handleSuccess(AsSuccessUnsafe) : elseValue;

    ///<summary>If the LocalizedTextCommandResult holds a Success, returns the result of invoking the <paramref name="handleSuccess"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns the result of invoking <paramref name="elseFunc"/>.</summary>
    ///<param name="handleSuccess">Function to be invoked with the Success value, if it exists.</param>
    ///<param name="elseFunc">Produces the value to be returned if the LocalizedTextCommandResult does not hold a Success</param>
    public TRet_ IfSuccessElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, TRet_> handleSuccess, global::System.Func<TRet_> elseFunc) => Index == 0 ? handleSuccess(AsSuccessUnsafe) : elseFunc();

    ///<summary>If the LocalizedTextCommandResult holds a Error, invokes the <paramref name="handleError"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise does nothing.</summary>
    ///<param name="handleError">Function to be invoked with the PlacesOfInterestMod.LocalizedText value, if it exists.</param>
    public void IfError(global::System.Action<PlacesOfInterestMod.LocalizedText> handleError)
    {
        if (Index == 1)
        {
            handleError(AsErrorUnsafe);
        }
    }

    ///<summary>If the LocalizedTextCommandResult holds a Error, invokes the <paramref name="handleError"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise invokes <paramref name="orElse"/>.</summary>
    ///<param name="handleError">Function to be invoked with the Error value, if it exists.</param>
    ///<param name="orElse">Function to be invoked if the LocalizedTextCommandResult does not hold a Error</param>
    public void IfErrorElse(global::System.Action<PlacesOfInterestMod.LocalizedText> handleError, global::System.Action orElse)
    {
        if (Index == 1)
        {
            handleError(AsErrorUnsafe);
        }
        else
        {
            orElse();
        }
    }

    ///<summary>If the LocalizedTextCommandResult holds a Error, returns the result of invoking the <paramref name="handleError"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns <paramref name="elseValue"/>.</summary>
    ///<param name="handleError">Function to be invoked with the Error value, if it exists.</param>
    ///<param name="elseValue">Value to be returned if the LocalizedTextCommandResult does not hold a Error</param>
    public TRet_ IfErrorElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, TRet_> handleError, TRet_ elseValue) => Index == 1 ? handleError(AsErrorUnsafe) : elseValue;

    ///<summary>If the LocalizedTextCommandResult holds a Error, returns the result of invoking the <paramref name="handleError"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns the result of invoking <paramref name="elseFunc"/>.</summary>
    ///<param name="handleError">Function to be invoked with the Error value, if it exists.</param>
    ///<param name="elseFunc">Produces the value to be returned if the LocalizedTextCommandResult does not hold a Error</param>
    public TRet_ IfErrorElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, TRet_> handleError, global::System.Func<TRet_> elseFunc) => Index == 1 ? handleError(AsErrorUnsafe) : elseFunc();

    ///<summary>If the LocalizedTextCommandResult holds a Success, invokes the <paramref name="SuccessHandler"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise does nothing.</summary>
    ///<param name="SuccessHandler">Function to be invoked with the PlacesOfInterestMod.LocalizedText value, if it exists.</param>
    public global::System.Threading.Tasks.ValueTask IfSuccess(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task> SuccessHandler) => Index == 0 ? new global::System.Threading.Tasks.ValueTask(SuccessHandler(AsSuccessUnsafe)) : global::System.Threading.Tasks.ValueTask.CompletedTask;

    ///<summary>If the LocalizedTextCommandResult holds a Success, invokes the <paramref name="SuccessHandler"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise invokes <paramref name="orElse">orElse</paramref>.</summary>
    ///<param name="SuccessHandler">Function to be invoked with the Success value, if it exists.</param>
    ///<param name="orElse">Function to be invoked if the LocalizedTextCommandResult does not hold a Success</param>
    public global::System.Threading.Tasks.Task IfSuccessElse(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task> SuccessHandler, global::System.Func<global::System.Threading.Tasks.Task> elseF) => Index == 0 ? SuccessHandler(AsSuccessUnsafe) : elseF();

    ///<summary>If the LocalizedTextCommandResult holds a Success, returns the result of invoking the <paramref name="SuccessHandler"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns <paramref name="elseValue"/> wrapped in a global::System.Threading.Tasks.ValueTask.</summary>
    ///<param name="SuccessHandler">Function to be invoked with the Success value, if it exists.</param>
    ///<param name="elseValue">Value to be returned if the LocalizedTextCommandResult does not hold a Success</param>
    public global::System.Threading.Tasks.ValueTask<TRet_> IfSuccessElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task<TRet_>> SuccessHandler, TRet_ elseValue) => Index == 0 ? new global::System.Threading.Tasks.ValueTask<TRet_>(SuccessHandler(AsSuccessUnsafe)) : global::System.Threading.Tasks.ValueTask.FromResult(elseValue);

    ///<summary>If the LocalizedTextCommandResult holds a Success, returns the result of invoking the <paramref name="SuccessHandler"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns the result of invoking <paramref name="elseFunc"/>.</summary>
    ///<param name="SuccessHandler">Function to be invoked with the Success value, if it exists.</param>
    ///<param name="elseFunc">Produces the value to be returned if the LocalizedTextCommandResult does not hold a Success</param>
    public global::System.Threading.Tasks.Task<TRet_> IfSuccessElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task<TRet_>> SuccessHandler, global::System.Func<global::System.Threading.Tasks.Task<TRet_>> elseFunc) => Index == 0 ? SuccessHandler(AsSuccessUnsafe) : elseFunc();

    ///<summary>If the LocalizedTextCommandResult holds a Error, invokes the <paramref name="ErrorHandler"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise does nothing.</summary>
    ///<param name="ErrorHandler">Function to be invoked with the PlacesOfInterestMod.LocalizedText value, if it exists.</param>
    public global::System.Threading.Tasks.ValueTask IfError(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task> ErrorHandler) => Index == 1 ? new global::System.Threading.Tasks.ValueTask(ErrorHandler(AsErrorUnsafe)) : global::System.Threading.Tasks.ValueTask.CompletedTask;

    ///<summary>If the LocalizedTextCommandResult holds a Error, invokes the <paramref name="ErrorHandler"/> function with the
    ///PlacesOfInterestMod.LocalizedText value, otherwise invokes <paramref name="orElse">orElse</paramref>.</summary>
    ///<param name="ErrorHandler">Function to be invoked with the Error value, if it exists.</param>
    ///<param name="orElse">Function to be invoked if the LocalizedTextCommandResult does not hold a Error</param>
    public global::System.Threading.Tasks.Task IfErrorElse(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task> ErrorHandler, global::System.Func<global::System.Threading.Tasks.Task> elseF) => Index == 1 ? ErrorHandler(AsErrorUnsafe) : elseF();

    ///<summary>If the LocalizedTextCommandResult holds a Error, returns the result of invoking the <paramref name="ErrorHandler"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns <paramref name="elseValue"/> wrapped in a global::System.Threading.Tasks.ValueTask.</summary>
    ///<param name="ErrorHandler">Function to be invoked with the Error value, if it exists.</param>
    ///<param name="elseValue">Value to be returned if the LocalizedTextCommandResult does not hold a Error</param>
    public global::System.Threading.Tasks.ValueTask<TRet_> IfErrorElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task<TRet_>> ErrorHandler, TRet_ elseValue) => Index == 1 ? new global::System.Threading.Tasks.ValueTask<TRet_>(ErrorHandler(AsErrorUnsafe)) : global::System.Threading.Tasks.ValueTask.FromResult(elseValue);

    ///<summary>If the LocalizedTextCommandResult holds a Error, returns the result of invoking the <paramref name="ErrorHandler"/>
    ///function with the PlacesOfInterestMod.LocalizedText value, otherwise returns the result of invoking <paramref name="elseFunc"/>.</summary>
    ///<param name="ErrorHandler">Function to be invoked with the Error value, if it exists.</param>
    ///<param name="elseFunc">Produces the value to be returned if the LocalizedTextCommandResult does not hold a Error</param>
    public global::System.Threading.Tasks.Task<TRet_> IfErrorElse<TRet_>(global::System.Func<PlacesOfInterestMod.LocalizedText, global::System.Threading.Tasks.Task<TRet_>> ErrorHandler, global::System.Func<global::System.Threading.Tasks.Task<TRet_>> elseFunc) => Index == 1 ? ErrorHandler(AsErrorUnsafe) : elseFunc();

    public override string ToString()
    {
        var (caseName, value) = Index switch
        {
            0 => ("Success", AsSuccessUnsafe is null ? "null" : AsSuccessUnsafe.ToString()),
            1 => ("Error", AsErrorUnsafe is null ? "null" : AsErrorUnsafe.ToString()),
        };

        return value is null ? caseName : $"{caseName} {value}";
    }

}
#pragma warning restore